# common
proj_name: airflow_train_pipeline_1
model_name: airflow_train_pipeline_1
model_version: v0.1

# Data Management
mart_id: dm_f_20085_2212_142

# workflow management
time_zone: Asia/Seoul
date_format: "%Y-%m-%d %H:%M:%S"

train_start_date: "2023-02-27 00:00:00"
train_schedule_interval: "@daily"

train_trigger_start_date: "2023-02-27 00:00:00"
train_trigger_schedule_interval: "@daily"

# training management
mlflow:
  tracking_uri: http://192.168.31.81:5000
  registry_uri: http://192.168.31.81:9000
  experiment_name: posml_project_1
  register_model: posml_project_1
  target_metric: accuracy_score
  target_metric_threshold: 0.9

minIO:
  aws_bucket_name: mlflow
  aws_access_key_id: posml
  aws_secret_access_key: posml123
  mlflow_s3_endpoint_url: http://192.168.31.81:9000/